### PR TITLE
Dividend Calendar

### PR DESCRIPTION
**Pull request by samkube**

### CODE REVIEW

**Comment by davidcaseria** [comment]
Hey @samkube, can you refactor this script so that the variable names are more intuitive? Also, can you change the Kimono API URL (on the Kimono website) to a URL with the date parameter i.e. http://www.nasdaq.com/dividend-stocks/dividend-calendar.aspx?date=2015-Feb-09?

**Comment by samkube** [comment]
@davidcaseria done, should I update the text file and create a new pull request?

**Comment by davidcaseria** [comment]
@samkube you should just change the file and commit to this pull request

**Comment by davidcaseria** [comment]
Perfect, thanks @samkube!

**Comment by samkube** [comment]
You bet, thank you @davidcaseria!

**Comment by samkube** [comment]
@davidcaseria we are having some crawling issues with the new URL, is that something I should manually reset or is there a better way to fix that?

**Comment by davidcaseria** [comment]
Under the Crawl Setup tab, set the auto-run frequency to manual. Since we have the date parameter in the URL now we can specifically request which dates we need instead of relying on Kimono the crawl the URLs for us.

**Comment by samkube** [comment]
Got it, that makes sense.  Thanks!

**Pull request merged**
